# Generated by Django 3.1.6 on 2021-04-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='desc',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
