# Generated by Django 3.1.6 on 2021-04-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210421_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Arm', 'Arm'), ('Leg', 'Leg'), ('Cardio', 'Cardio'), ('Abs', 'Abs')], max_length=50)),
                ('rep_type', models.CharField(choices=[('Sets', 'Sets')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Arm', 'Arm'), ('Leg', 'Leg'), ('Cardio', 'Cardio'), ('Abs', 'Abs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.machines'),
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
