# Generated by Django 3.1.3 on 2021-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_20210421_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Arm', 'Arm'), ('Leg', 'Leg'), ('Cardio', 'Cardio')], max_length=50)),
                ('rep_type', models.CharField(choices=[('Sets', 'Sets')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
    ]
